language: node_js
cache:
  directiories: 
    - ~/.npm
node_js:
  - '9'
git:
  depth: 3
script: 
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-toke: $GITHUB_TOKEN
  local-dist: dist/
  target-branch: master
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on:
    branch: develop